version: "3"
services:
  # TODO
  # - [x] grafana
  # - [ ] tempo
  # - [ ] loki
  # - [ ] prometheus
  # - [ ] otel collector
  # webapp:
  #   build: . # Path to your Dockerfile
  #   ports:
  #     - "8080:8080"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./data/var/lib/grafana:/var/lib/grafana
    ports:
      - "3000:3000"

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./docker/:/etc/
      - ./data/var/tempo:/var/tempo
    ports:
      - "3200:3200" # tempo
      - "4318" # otlp http
      - "4317" # otlp grpc

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./docker/:/etc/
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.82.0
    restart: always
    command:
      - --config=/etc/otel-collector.yml
    volumes:
      - ./docker/:/etc/
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension


  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus
  #   restart: always
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   volumes:
  #     - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # tempo:
  #   image: grafana/tempo:latest
  #   command: ["-config.file=/etc/tempo.yml"]
  #   volumes:
  #     - ./docker/tempo/tempo.yml:/etc/tempo.yml
  #   ports:
  #     - "3200:3200" # tempo
  #     - "4317" # otlp grpc

  # loki:
  #   image: grafana/loki:latest
  #   command: -config.file=/etc/loki/local-config.yaml
  #   ports:
  #     - "3100:3100"

  # # grafana:
  # #   container_name: grafana
  # #   image: grafana/grafana
  # #   ports:
  # #     - "3000:3000"
# volumes:
#   stanley-data:
